//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsnovnaSkola
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domaci : Kontrolna_tacka
    {
        public System.DateTime dan_zadavanja { get; set; }
        public System.DateTime dan_predaje { get; set; }
    }
}
