//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsnovnaSkola
{
    using System;
    using System.Collections.Generic;
    
    public partial class NastavnikOdeljenje
    {
        public int NastavnikId_zaposlenog { get; set; }
        public int OdeljenjeId_odeljenja { get; set; }
        public bool Razredni { get; set; }
    
        public virtual Nastavnik Nastavnik { get; set; }
        public virtual Odeljenje Odeljenje { get; set; }
    }
}
