//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsnovnaSkola
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predavanje
    {
        public int Id_predavanja { get; set; }
        public string opis { get; set; }
        public System.DateTime datum_odrzavanja { get; set; }
        public int OblastId_oblasti { get; set; }
        public int ZaposleniId_zaposlenog { get; set; }
    
        public virtual Oblast Oblast { get; set; }
        public virtual Zaposleni Zaposleni { get; set; }
    }
}
