//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsnovnaSkola
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prisustvo
    {
        public int UcenikId_ucenika { get; set; }
        public int CasId_casa { get; set; }
        public int ZaposleniId_zaposlenog { get; set; }
    
        public virtual Ucenik Ucenik { get; set; }
        public virtual Cas Cas { get; set; }
        public virtual Zaposleni Zaposleni { get; set; }
    }
}
