
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OsnovnaSkola
{

using System;
    using System.Collections.Generic;
    
public partial class Ucionica
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Ucionica()
    {

        this.ZauzetostUcionices = new HashSet<ZauzetostUcionice>();

    }


    public int Id_ucionice { get; set; }

    public int broj_ucenika { get; set; }

    public string naziv { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ZauzetostUcionice> ZauzetostUcionices { get; set; }

}

}
