
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OsnovnaSkola
{

using System;
    using System.Collections.Generic;
    
public partial class Zaposleni
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Zaposleni()
    {

        this.Kontrolna_tacka = new HashSet<Kontrolna_tacka>();

        this.Casovi = new HashSet<Cas>();

        this.Prisustva = new HashSet<Prisustvo>();

        this.Radovi = new HashSet<Radi>();

        this.Predavanja = new HashSet<Predavanje>();

    }


    public int Id_zaposlenog { get; set; }

    public string zvanje { get; set; }

    public string korisnicko_ime { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Kontrolna_tacka> Kontrolna_tacka { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Cas> Casovi { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Prisustvo> Prisustva { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Radi> Radovi { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Predavanje> Predavanja { get; set; }

}

}
