//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsnovnaSkola
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZauzetostUcionice
    {
        public int Id_zauzetosti { get; set; }
        public int UcionicaId_ucionice { get; set; }
        public System.TimeSpan pocetak { get; set; }
        public System.DateTime datum { get; set; }
        public int OdeljenjeId_odeljenja { get; set; }
    
        public virtual Ucionica Ucionica { get; set; }
        public virtual Cas Cas { get; set; }
        public virtual Odeljenje Odeljenje { get; set; }
    }
}
